// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tljsbmpglwmzyaoxsqyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsanNibXBnbHdtenlhb3hzcXlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NTUyMDgsImV4cCI6MjA3NjMzMTIwOH0.N62jwp7KE09a2WrftnH2bGB4gbajY0bTLt4_pQnefS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});